[package]
  cjc-version = "1.0.0"
  name = "xquest"
  description = "XQuest game"
  version = "0.1.1"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  cjsfml = { path = "dependencies/cjsfml", output-type = "dynamic" }
  customiterators = { path = "dependencies/customiterators", output-type = "dynamic" }
  dgengine = { path = "dependencies/dgengine", output-type = "dynamic" }
  endian = { path = "dependencies/endian", output-type = "dynamic" }
  stdjson2 = { path = "dependencies/stdjson2", output-type = "dynamic" }
  stdlog = { path = "dependencies/stdlog", output-type = "dynamic" }
