package cjsfml.audio

import cenum.CEnum

@CEnum[public SoundChannel](
    Unspecified
    Mono
    FrontLeft
    FrontRight
    FrontCenter
    FrontLeftOfCenter
    FrontRightOfCenter
    LowFrequencyEffects
    BackLeft
    BackRight
    BackCenter
    SideLeft
    SideRight
    TopCenter
    TopFrontLeft
    TopFrontRight
    TopFrontCenter
    TopBackLeft
    TopBackRight
    TopBackCenter
)
