name: CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      APP_NAME: DGEngine
      CANGJIE_VERSION: 1.0.5
    steps:
      - name: Checkout ${{ env.APP_NAME }}
        uses: actions/checkout@v6

      - name: Install Ubuntu dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev
          version: 1.0
          execute_install_scripts: true

      - name: Build and install SFML
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: sfml
          triplet: x64-linux
          extra-args: --overlay-ports=../dependencies/vcpkg
          cache-key: vcpkg-ubuntu-latest
          token: ${{ secrets.GITHUB_TOKEN }}
          revision: '84bab45d415d22042bd0b9081aea57f362da3f35'  # 2025.12.12

      - name: Build and install CSFML
        run: |
          git clone --branch feature/right-align-text-3 https://github.com/dgcor/CSFML.git dependencies/csfml
          cp -f dependencies/CMakePresets.json dependencies/csfml/CMakePresets.json
          cd dependencies/csfml
          cmake --preset linux-release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build --preset linux-release --target install

      - name: Setup Cangjie
        uses: Zxilly/setup-cangjie@v2
        with:
          channel: lts
          version: ${{ env.CANGJIE_VERSION }}
          archive-path: ./cangjie-archive

      - name: Build ${{ env.APP_NAME }}
        run: cjpm build

      - name: Test ${{ env.APP_NAME }}
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          cjpm test
