[package]
  cjc-version = "1.0.0"
  name = "dgengine"
  description = "DGEngine game engine"
  version = "2.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  cenum = { path = "../cenum" }
  cjsfml = { path = "../cjsfml" }
  ctemplate = { path = "../ctemplate" }
  customiterators = { path = "../customiterators" }
  endian = { path = "../endian" }
  physfs4cj = { path = "../physfs4cj" }
  stdjson2 = { path = "../stdjson2" }
  stdlog = { path = "../stdlog" }
