[package]
  cjc-version = "1.0.0"
  name = "ctemplate"
  description = "ctemplate - C++ like template macro"
  version = "1.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std --dy-libs -O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
