[package]
  cjc-version = "1.0.0"
  name = "cenum"
  description = "C enum macro"
  version = "1.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std -O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
