[package]
  cjc-version = "1.0.0"
  name = "tennis"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = "-s"
  package-configuration = {}

[dependencies]
  cjsfml = { path = "./../../" }
